spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/marketit
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
    hikari:
      connection-test-query: SELECT 1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true